routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth'], function() {
	Route::get('/home', 'HomeController')->name('home');

	Route::resource('leave-request', 'LeaveRequestController', [
		'parameters' => [
			'leave-request' => 'leaveRequest'
		],
		'except' => ['edit', 'update']
	]);
	Route::put('leave-request/{leaveRequest}/accept', 'LeaveRequestController@accept')->name('leave-request.accept');
	Route::delete('leave-request/{leaveRequest}/reject', 'LeaveRequestController@reject')->name('leave-request.reject');

	Route::group(['prefix' => 'dashboard', 'middleware' => 'isAdmin'], function() {

		Route::get('/', function() {
			return view('dashboard');
		})->name('dashboard');

		Route::resource('leave-type', 'LeaveTypeController', [
			'except' => ['show']
		]);

		Route::get('logs', function() {
			$users = Koala\User::all();

			return view('logs')->with(compact('users'));
		})->name('logs');
		
	});

	Route::resource('message', 'MessageController', [
		'only' => ['store']
	]);

	Route::get('profile/{user}', 'ProfileController')->name('profile');

	Route::get('logout', function() {
		auth()->logout();
		return redirect(route('welcome'));
	})->name('logout');
});

Route::group(['middleware' => 'guest'], function() {
	Route::get('/', function() {
		return view('welcome');
	})->name('welcome');
	Route::get('login/{provider?}', 'OAuthController@login')->name('oauth.login');
	Route::get('login/{provider?}/callback', 'OAuthController@callback')->name('oauth.callback');
});

Route::get('/kokowawa/{id}', function($id) {
	auth()->loginUsingId($id);
	return back();
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="/css/app.css" rel="stylesheet">

    <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ url('/login') }}">Login</a></li>
                            <li><a href="{{ url('/register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ url('/logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="/js/app.js"></script>
</body>
</html>

resources/views/layouts/errors.blade.php
@if (count($errors) > 0)
    <div class="alert alert-danger alert-important">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Koala | Accorpa</title>
		<meta name="csrf-token" content="{{ csrf_token() }}">
		<meta name="csrf-param" content="_token" />

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" type="text/css" href="{{ asset('css/all.css') }}">

		<script>
		    window.Koala = <?php echo json_encode([
		        'csrfToken' => csrf_token(),
		    ]); ?>
		</script>

		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>
		@include('layouts.navbar')

		<div class="container">
			<div class="row">
				<div class="col-xs-12 col-md-6 col-md-offset-3">
					@include('flash::message')
				</div>	
			</div>

			@yield('content')
		</div>

		<script type="text/javascript" src="{{ asset('js/app.js') }}"></script>
		<script type="text/javascript" src="{{ asset('js/all.js') }}"></script>
		<script type="text/javascript">
			$('div.alert').not('.alert-important').delay(7000).fadeOut('slow');
			$('.selectpicker').selectpicker({
			  style: 'btn-primary',
			  size: 7
			});
			$('.datepicker').datepicker({
				format: "yyyy-mm-dd",
			    startDate: "today",
			    todayBtn: "linked",
			    clearBtn: true,
			    daysOfWeekDisabled: [5, 6]
			});
		</script>
	</body>
</html>

resources/views/layouts/navbar.blade.php
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ route('home') }}">
        Koala
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        @if(auth()->user() && auth()->user()->type === 'admin')
          <li>
            <a href="{{ route('leave-request.index') }}"> Leave Requests <span class="badge">{{ $leaveRequestsCount }}</span> </a>
          </li>
          <li>
            <a href="{{ route('dashboard') }}"> Dashboard </a>
          </li>
        @endif
      </ul>

      @if(auth()->user())
        <ul class="nav navbar-nav navbar-right">
          <li>
            <a href="{{ route('profile', auth()->id()) }}"> 
              {{ auth()->user()->name }}
            </a>
          </li>
          <li>
            <a href="{{ route('logout') }}">
              Logout
              <i class="fa fa-sign-out"></i>
            </a>
          </li>
        </ul>
      @endif
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>